FORMAT: 1A

# Selector Metodologías

El selector de metodologías sugiere una metodología de software a utilizar en
un proyecto de software en base a las necesidades y contexto de dicho proyecto.

# Group Preguntas

## Colección de Preguntas [/questions]

### Listar todas las preguntas [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "question": "Es el presupuesto para el proyecto limitado?",
                "criteria": "Dimensión del proyecto",
                "evaluations":
                [
                    {
                        "methodology": 1,
                        "evaluation": 3
                    },
                    {
                        "methodology": 2,
                        "evaluation": 1
                    },
                    {
                        "methodology": 3,
                        "evaluation": 5
                    }
                ]
            }
        ]

### Crear nueva pregunta [POST]

+ Attributes

    + question: ¿La dimesión del proyecto se considera grande? (string) - Pregunta que se añadirá al sistema.
    + evaluations (array) - Lista con la ponderación de la pregunta para cada metodología. Si la lista esta incompleta se dará una ponderación por default de `0` para las metodologías no específicadas.
        + (object)
            + methodology: 1 (string) - ID de la metodología a la que corresponde la ponderación.
            + evaluation: 3 (string) - Ponderación dada a la metodología para esta pregunta. El valor dado debe estar en el rango `[1..5]` si se especifica otro valor se producirá un error.

+ Request (application/json)

        {
            "question": "La dimensión del proyecto se considera grande?",
            "evaluations":
            [
                {
                    "methodology": 1,
                    "evaluation": 3
                },
                {
                    "methodology": 2,
                    "evaluation": 1
                },
                {
                    "methodology": 3,
                    "evaluation": 5
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "id": 2,
                "question": "La dimensión del proyecto se considera grande?",
                "evaluations":
                [
                    {
                        "methodology": 1,
                        "evaluation": 3
                    },
                    {
                        "methodology": 2,
                        "evaluation": 1
                    },
                    {
                        "methodology": 3,
                        "evaluation": 5
                    }
                ]
            }


## Pregunta [/questions/{question_id}]

+ Parameters
    + question_id: `1` (number, required) - ID numérico de la pregunta que desea manipular.

### Consultar detalles de una pregunta [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "question": "La dimensión del proyecto se considera grande?",
            "evaluations":
            [
                {
                    "methodology": 1,
                    "evaluation": 3
                },
                {
                    "methodology": 2,
                    "evaluation": 1
                },
                {
                    "methodology": 3,
                    "evaluation": 5
                }
            ]
        }

### Editar una pregunta [PUT]

Solo se modificarán los atributos específicados en el request.

+ Attributes

    + question: ¿La dimesión del proyecto se considera amplia? (string) - Pregunta con la modificiación que se actualizará en el sistema.
    + evaluations (array) - Lista con la ponderación de la pregunta para cada metodología.
        + (object).
            + methodology: 1 (string) - ID de la metodología a la que corresponde la ponderación.
            + evaluation: 3 (string) - Ponderación dada a la metodología para esta pregunta. El valor dado debe estar en el rango `[1..5]` si se especifica otro valor se producirá un error.

+ Request (application/json)

        {
            "question": "La dimensión del proyecto se considera amplia?",
            "evaluations":
            [
                {
                    "methodology": 1,
                    "evaluation": 1
                },
                {
                    "methodology": 2,
                    "evaluation": 5
                },
                {
                    "methodology": 3,
                    "evaluation": 3
                }
            ]
        }

+ Response 200 (application/json)

        {
            "id": 2,
            "question": "La dimensión del proyecto se considera grande?",
            "evaluations":
            [
                {
                    "methodology": 1,
                    "evaluation": 1
                },
                {
                    "methodology": 2,
                    "evaluation": 5
                },
                {
                    "methodology": 3,
                    "evaluation": 3
                }
            ]
        }

### Eliminar una pregunta [DELETE]

+ Response 204


# Group Metodologías

## Colección de Metodologías [/methodologies]

### Listar todas las metodologías [GET]

+ Response 200 (application/json)

        [
            {
                "id": 223,
                "name": "Scrum",
                "links": [
                    {
                        "href": "methodologies/223",
                        "rel": "self",
                        "type": "GET"
                    }
                ]
            },
            {
                "id": 221,
                "name": "Xtreme Programming",
                "links": [
                    {
                        "href": "methodologies/221",
                        "rel": "self",
                        "type": "GET"
                    }
                ]
            }
        ]

### Crear una metodología [POST]

+ Request (application/json)

        {
            "name": "Rup",
            "abstract": "Bla bla bla bla",
            "quality_features": "Bla bla bla bla",
            "info": "http://..../rup.html",
            "type": "tradicional",
            "model": "espiral",
            "diagrams": {
                "process": "http://....../rup/process.png",
                "roles": "http://......../rup/roles.jpg",
                "artifacts": "http://......../rup/artifacts.jpeg",
                "practices": "http://......../rup/practices.jpeg"
            },
            "description": {
                "process": [
                    {
                        "stage": 1,
                        "name": "Inception",
                        "description": "The idea for the project is stated. The development team determines...",
                        "image": "http://...../rup/stage/1/inception.jpg"
                    },
                    {
                        "stage": 2,
                        "name": "Elaboration",
                        "description": "The project's architecture and required resources are further evaluated...",
                        "image": "http://...../rup/stage/2/elaboration.jpg"
                    },
                    {
                        "stage": 3,
                        "name": "Construction",
                        "description": "The project is developed and completed.",
                        "image": "http://...../rup/stage/3/construction.jpg"
                    },
                    {
                        "stage": 4,
                        "name": "Transition",
                        "description": "The software is released to the public",
                        "image": "http://...../rup/stage/4/transition.jpg"
                    }
                ],
                "roles": [
                    {
                        "name": "Senior developer",
                        "description": "Bla bla bla bla",
                        "image": "http://...../rup/role/1/avatar.jpg",
                        "produces_artifact": "Pruebas automatizadas"
                    },
                    {
                        "name": "Team leader",
                        "description": "Bla bla bla bla",
                        "image": "http://...../rup/role/2/avatar.jpg",
                        "produces_artifact": ""
                    }
                ],
                "artifacts": [
                    {
                        "id": 1,
                        "name": "Code documentation",
                        "description": "Bla bla bal",
                        "image": "http://..../rup/artifact/1/documentation.jpg"
                    }
                ],
                "practices": [
                    {
                        "name": "Pair programming",
                        "description": "Bla bla bla",
                        "image": "http://....../rup/practices/1/ppg.png"
                    },
                    {
                        "tdd": "Test driven development",
                        "description": "Bla bla bla",
                        "image": "http://...../rup/practices/2/tdd.jpeg"
                    }
                ],
                "tips": [
                    {
                        "description": "Bla bla bla",
                    },
                ],
                "tools": [
                    {
                        "name": "Trello",
                        "description": "Bla bla bla",
                        "link": "http://trello.com"
                    },
                ]
            }
        }

+ Response 201 (application/json)

    Cambiar "produces artifact"

    + Headers

            Location: /methodologies/3

    + Body

            {
                "id": 3,
                "name": "Rup",
                "abstract": "Bla bla bla bla",
                "info": "http://..../rup.html",
                "type": "tradicional",
                "quality_features": "Bla bla bla bla",
                "model": "espiral",
                "diagrams": {
                    "process": "http://....../rup/process.png",
                    "roles": "http://......../rup/roles.jpg",
                    "artifacts": "http://......../rup/artifacts.jpeg",
                    "practices": "http://......../rup/practices.jpeg",
                },
                "description": {
                    "process": [
                        {
                            "stage": 1,
                            "name": "Inception",
                            "description": "The idea for the project is stated. The development team determines...",
                            "image": "http://...../rup/stage/1/inception.jpg"
                        },
                        {
                            "stage": 2,
                            "name": "Elaboration",
                            "description": "The project's architecture and required resources are further evaluated...",
                            "image": "http://...../rup/stage/2/elaboration.jpg"
                        },
                        {
                            "stage": 3,
                            "name": "Construction",
                            "description": "The project is developed and completed.",
                            "image": "http://...../rup/stage/3/construction.jpg"
                        },
                        {
                            "stage": 4,
                            "name": "Transition",
                            "description": "The software is released to the public",
                            "image": "http://...../rup/stage/4/transition.jpg"
                        }
                    ],
                    "roles": [
                        {
                            "name": "Senior developer",
                            "description": "Bla bla bla bla",
                            "image": "http://...../rup/role/1/avatar.jpg",
                            "produces_artifact": 1
                        },
                        {
                            "name": "Team leader",
                            "description": "Bla bla bla bla",
                            "image": "http://...../rup/role/2/avatar.jpg",
                            "produces_artifact": null
                        }
                    ],
                    "artifacts": [
                        {
                            "id": 1,
                            "name": "Code documentation",
                            "description": "Bla bla bal",
                            "image": "http://..../rup/artifact/1/documentation.jpg"
                        }
                    ],
                    "practices": [
                        {
                            "name": "Pair programming",
                            "description": "Bla bla bla",
                            "image": "http://....../rup/practices/1/ppg.png"
                            "produces_artifact": null,
                        },
                        {
                            "tdd": "Test driven development",
                            "description": "Bla bla bla",
                            "image": "http://...../rup/practices/2/tdd.jpeg",
                            "produces_artifact": 1
                        }
                    ]
                }
            }

## Metodología [/methodologies/{methodology_id}]

+ Parameters
    + methodology_id: `1` (number, required) - ID numérico de la metodología que desea manipular.

### Consultar detalles de una metodología [GET]

+ Response 200 (application/json)

        {
            "id": 223,
            "name": "Rup",
            "abstract": "Bla bla bla bla",
            "quality_features": "Bla bla bla bla",
            "info": "http://..../rup.html",
            "type": "tradicional",
            "model": "espiral",
            "diagrams": {
                "process": "http://....../rup/process.png",
                "roles": "http://......../rup/roles.jpg",
                "artifacts": "http://......../rup/artifacts.jpeg",
                "practices": "http://......../rup/practices.jpeg",
            },
            "description": {
                "process": [
                    {
                        "stage": 1,
                        "name": "Inception",
                        "description": "The idea for the project is stated. The development team determines...",
                        "image": "http://...../rup/stage/1/inception.jpg"
                    },
                    {
                        "stage": 2,
                        "name": "Elaboration",
                        "description": "The project's architecture and required resources are further evaluated...",
                        "image": "http://...../rup/stage/2/elaboration.jpg"
                    },
                    {
                        "stage": 3,
                        "name": "Construction",
                        "description": "The project is developed and completed.",
                        "image": "http://...../rup/stage/3/construction.jpg"
                    },
                    {
                        "stage": 4,
                        "name": "Transition",
                        "description": "The software is released to the public",
                        "image": "http://...../rup/stage/4/transition.jpg"
                    }
                ],
                "roles": [
                    {
                        "name": "Senior developer",
                        "description": "Bla bla bla bla",
                        "image": "http://...../rup/role/1/avatar.jpg",
                        "produces_artifact": 1
                    },
                    {
                        "name": "Team leader",
                        "description": "Bla bla bla bla",
                        "image": "http://...../rup/role/2/avatar.jpg",
                        "produces_artifact": null
                    }
                ],
                "artifacts": [
                    {
                        "id": 1,
                        "name": "Code documentation",
                        "description": "Bla bla bal",
                        "image": "http://..../rup/artifact/1/documentation.jpg"
                    }
                ],
                "practices": [
                    {
                        "name": "Pair programming",
                        "description": "Bla bla bla",
                        "image": "http://....../rup/practices/1/ppg.png"
                        "produces_artifact": null,
                    },
                    {
                        "tdd": "Test driven development",
                        "description": "Bla bla bla",
                        "image": "http://...../rup/practices/2/tdd.jpeg",
                        "produces_artifact": 1
                    }
                ]
            }
        }

### Editar una metodología [PUT]

+ Request (application/json)

        {
            "name": "Rup",
            "abstract": "This is the abstract for this methodology."
            "description": {
                "process": "Bla bla bla bla bla",
            }
        }

+ Response 200 (application/json)

        {
            "id": 223,
            "name": "Rup",
            "abstract": "This is the abstract for this methodology.",
            "quality_features": "Bla bla bla bla",
            "info": "http://..../rup.html",
            "type": "tradicional",
            "model": "espiral",
            "diagrams": {
                "process": "http://....../rup/process.png",
                "roles": "http://......../rup/roles.jpg",
                "artifacts": "http://......../rup/artifacts.jpeg",
                "practices": "http://......../rup/practices.jpeg",
            },
            "description": {
                "process": [
                    {
                        "stage": 1,
                        "name": "Inception",
                        "description": "The idea for the project is stated. The development team determines...",
                        "image": "http://...../rup/stage/1/inception.jpg"
                    },
                    {
                        "stage": 2,
                        "name": "Elaboration",
                        "description": "The project's architecture and required resources are further evaluated...",
                        "image": "http://...../rup/stage/2/elaboration.jpg"
                    },
                    {
                        "stage": 3,
                        "name": "Construction",
                        "description": "The project is developed and completed.",
                        "image": "http://...../rup/stage/3/construction.jpg"
                    },
                    {
                        "stage": 4,
                        "name": "Transition",
                        "description": "The software is released to the public",
                        "image": "http://...../rup/stage/4/transition.jpg"
                    }
                ],
                "roles": [
                    {
                        "name": "Senior developer",
                        "description": "Bla bla bla bla",
                        "image": "http://...../rup/role/1/avatar.jpg",
                        "produces_artifact": 1
                    },
                    {
                        "name": "Team leader",
                        "description": "Bla bla bla bla",
                        "image": "http://...../rup/role/2/avatar.jpg",
                        "produces_artifact": null
                    }
                ],
                "artifacts": [
                    {
                        "id": 1,
                        "name": "Code documentation",
                        "description": "Bla bla bal",
                        "image": "http://..../rup/artifact/1/documentation.jpg"
                    }
                ],
                "practices": [
                    {
                        "name": "Pair programming",
                        "description": "Bla bla bla",
                        "image": "http://....../rup/practices/1/ppg.png"
                        "produces_artifact": null,
                    },
                    {
                        "tdd": "Test driven development",
                        "description": "Bla bla bla",
                        "image": "http://...../rup/practices/2/tdd.jpeg",
                        "produces_artifact": 1
                    }
                ]
            }
        }


### Eliminar una metodología [DELETE]

+ Response 204

# Group Feedback

## Colección de Feedback [/feedback]

### Listar las entradas en Feedback [GET]

+ Response 200 (application/json)

        [
            {
                "id": "4k0f4c31aaa35d6b867dae9a7f5427t3",
                "institution": "UAZ",
                "created_at": "2013-10-02T01:11:18.965Z",
                "email": "algo@mail.com",
                "finished": 0,
                "description": "Bla bla bla bla"
            },
            {
                "id": "3t7245f7a9ead768b6d53aaa13c4f0k4",
                "institution": "ITZ",
                "created_at": "2013-10-02T01:11:18.965Z",
                "email": "otro@mail.com",
                "finished": 0,
                "description": "Bla bla bla bla"
            },
        ]

### Enviar feedback [POST]

+ Request (application/json)

        {
            "institution": "UAZ",
            "email": "algo@mail.com"
        }

+ Response 201 (application/json)

    + Headers

            Location: /feedback/4k0f4c31aaa35d6b867dae9a7f5427t3

    + Body

            {
                "id": "4k0f4c31aaa35d6b867dae9a7f5427t3",
                "institution": "UAZ",
                "email": "algo@mail.com"
            }

## Feedback [/feedback/{feedback_id}]

+ Parameters
    + feedback_id: `4k0f4c31aaa35d6b867dae9a7f5427t3` (string, required) -
      Cadena de identificación de la retroalimentación que desea manipular.

### Consultar una retroalimentación [GET]

+ Response 200 (application/json)

        {
            "id": "4k0f4c31aaa35d6b867dae9a7f5427t3",
            "created_at": "2013-10-02T01:11:18.965Z",
            "institution": "UAZ",
            "email": "algo@mail.com",
            "finished": 1,
            "description": "Bla bla bla bla"
        }

### Editar una retroalimentación [PUT]

+ Request (application/json)

        {
            "description": "There's a meaning in this message."
        }

+ Response 200 (application/json)

        {
            "id": "4k0f4c31aaa35d6b867dae9a7f5427t3",
            "created_at": "2013-10-02T01:11:18.965Z",
            "institution": "UAZ",
            "email": "algo@mail.com",
            "finished": 1,
            "description": "There's a meaning in this message."
        }

### Eliminar una retroalimentación [DELETE]

+ Response 204


# Group Sugerencia

## Colección de recomendación [/suggest]

### Generar una recomendación [POST]

- Si el `value` indicado para cualquier respuesta en la petición no es `1` o `0` se producirá un error, ya que por ahora las preguntas son de respuesta binaria.

- Si no se especifica una pregunta se asume que se contestó `0` (`No`).

+ Attributes (array)
    + (object)
        + question: 1 (number) - ID de la pregunta a la cual corresponde la respuesta (`value`) asociada.
        + value: 0 (number) - `0` indica `No` y `1` indica `Si`.

+ Request (application/json)

        [
            {
                "question": 1,
                "value": 0
            },
            {
                "question": 2,
                "value": 1
            }
        ]


+ Response 201 (application/json)

    + Headers

            Location: /suggest/916f4c31aaa35d6b867dae9a7f54270d

    + Body

            {
                "name": "Scrum",
                "score" 23,
                "links": [
                    {
                        "href": "methodologies/223",
                        "rel": "methodologies",
                        "type": "GET"
                    }
                ]
            }
