#!/usr/bin/env bash

echo -e "\033[1;33m[ GO API TODO LIST ]\033[0m" && grep -nr 'TODO' --exclude-dir=vendor api/**/*.go

echo -e "\033[1;33m[ ELM APP TODO LIST ]\033[0m" && grep -nr 'TODO' --exclude-dir=elm-stuff app/**/*.elm
