language: go

sudo: false

go: "1.10.x"

before_install:
  - go get -v -u golang.org/x/lint/golint
  - go get -v -u github.com/golang/dep/cmd/dep

before_script:
  - dep ensure -v

script:
  - ./linter
  - go test -cpu=1,2 -v ./...
